version: '3'

services:
  database:
    container_name: database_mariadb
    image: 'mariadb:10.1.22'
    ports:
      - '3306:3306' # Database
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'tdin'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
